onboarding = false

[ui]
show_agent_labels_on_pane_borders = true
sidebar_start_collapsed = true
prompt_new_tab_name = false
prompt_new_workspace_name = false

[ui.toast.clipboard]
enabled = false

[theme]
name = "catppuccin"
auto_switch = false
