# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 600

# Disable the package module, hiding it from the prompt completely
package.disabled = true
line_break.disabled = true
cmd_duration.disabled = true
aws.disabled = true
python.disabled = true
golang.disabled = true
rust.disabled = true
nodejs.disabled = true

[hostname]
ssh_only = false
format = '(bold red)[$hostname]($style)\] '
trim_at = '.'

[os]
#disabled = false

[time]
disabled = false
use_12hr = false

[username]
show_always = true
format = '\[[$user](bold yellow) at (bold red)($style)'
