#!/usr/bin/env python3
# -*- coding: utf8 -*-
# vim:ts=4 sts=4 sw=4 et

from pathlib import Path

__author__ = 'Antonio Dias'
__email__ = 'accdias@gmail.com'
__copyright__ = 'Copyright (C)@YEAR@, Antonio Dias'
__license__ = 'GPL'
__version__ = '0.1'
__status__ = 'Development'

config_yaml = Path('~/.config/project/config.yaml')
