#!/usr/bin/env python
import os
import sys
import re
# Last modified:

__author__ = 'Antonio Dias'
__email__ = 'accdias@gmail.com'
__copyright__ = 'Copyright 2017, Antonio Dias'
__license__ = 'GPL'
__version__ = '0.1'
__status__ = 'Development'


if __name__ == '__main__':
    invoke_the_real_code()

# coding: utf-8
# vim:ts=4:sts=4:sw=4:et