# ~/.bash_aliases
case "$OSTYPE" in
    linux*)
	OSCODENAME="linux"
	;;
    cygwin)
	OSCODENAME="cygwin"
	;;
    darwin*)
        OSCODENAME="macos"
        ;;
    *)
        ;;
esac

if test -r ~/.bashrc.d/bash_aliases.${OSCODENAME}; then
    source ~/.bashrc.d/bash_aliases.${OSCODENAME}
fi
