# ~/.bash_aliases
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
# alias df='df -h'
# alias du='du -h'
#
# Misc :)
alias less='less -r'                              # raw control characters
# alias whence='type -a'                          # where, of a sort
alias grep='grep --color'                         # show differences in colour
alias cgrep='egrep -v "^\s*(#|;|$)" --color=auto' # strip comments from files
alias egrep='egrep --color=auto'                  # show differences in colour
alias fgrep='fgrep --color=auto'                  # show differences in colour
#
# Some shortcuts for different directory listings
alias ls='ls -hF --color=tty --group-directories-first' # classify files in colour show directories on top
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
# alias ll='ls -l'                              # long list
# alias la='ls -A'                              # all but . and ..
# alias l='ls -CF'                              #
alias sumfile="awk 'BEGIN{s=0}{s=s+\$0}END{print s}'" # give the sum of values from a file
alias getmp3='youtube-dl --extract-audio --audio-format mp3 --audio-quality 9 $@'
alias getogg='youtube-dl --extract-audio --audio-format vorbis --audio-quality 9 $@'

case "$OSTYPE" in
    linux*)
		OSCODENAME=$(lsb_release -sc)
	;;
    cygwin)
		OSCODENAME="cygwin"
	;;
    *)
        ;;
esac

case "${OSCODENAME,,}" in
    twentytwo|twentythree|twentyfour)
		source ~/.bashrc.d/bash_aliases.fedora
	;;
    utopic|karmic|lucid)
		source ~/.bashrc.d/bash_aliases.ubuntu
	;;
    cygwin)
		source ~/.bashrc.d/bash_aliases.cygwin
	;;
    *)
	;;
esac
